using System.Net;
using System.Security.AccessControl;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Security.Principal;

namespace TivuStream.Pie.Api.Transport;

/// <summary>
/// The certificate PIE generates for itself when the operator provides none.
/// </summary>
/// <remarks>
/// Transport Security Specification, Generated By PIE. For this server only:
/// it cannot sign other certificates, so whoever obtained its key could
/// impersonate PIE and nothing else.
/// </remarks>
internal static class GeneratedCertificate
{
    internal const string FileName = "pie.pfx";

    /// <summary>
    /// The longest validity every browser accepts.
    /// </summary>
    internal static readonly TimeSpan Validity = TimeSpan.FromDays(397);

    /// <summary>
    /// How long before expiry a new certificate is generated.
    /// </summary>
    internal static readonly TimeSpan RenewalMargin = TimeSpan.FromDays(30);

    /// <summary>
    /// Returns the certificate kept in <paramref name="directory"/>, or a new
    /// one when there is none, it is about to expire, it no longer names this
    /// computer, or it cannot be read.
    /// </summary>
    /// <param name="directory">Where the certificate is kept.</param>
    /// <param name="names">Names and addresses of this computer.</param>
    /// <param name="now">The present instant.</param>
    /// <returns>The certificate, and whether it was generated now.</returns>
    internal static (X509Certificate2 Certificate, bool Generated) LoadOrCreate(
        string directory,
        MachineNames names,
        DateTimeOffset now)
    {
        string path = Path.Combine(Path.GetFullPath(directory), FileName);

        if (File.Exists(path))
        {
            try
            {
                X509Certificate2 kept = X509CertificateLoader.LoadPkcs12FromFile(path, password: null);

                if (!NeedsRenewal(kept, names, now))
                {
                    return (kept, false);
                }

                kept.Dispose();
            }
            catch (CryptographicException)
            {
                // Unreadable: replaced below, as if it were absent. It is
                // PIE's own file, not one the operator chose.
            }
        }

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        using X509Certificate2 created = Create(names, now);

        WriteProtected(path, created.Export(X509ContentType.Pkcs12));

        // Read back from the file, so that the key is held the way the
        // operating system's TLS stack expects of a persisted certificate.
        return (X509CertificateLoader.LoadPkcs12FromFile(path, password: null), true);
    }

    /// <summary>
    /// Creates a certificate for this server, naming every name and address.
    /// </summary>
    internal static X509Certificate2 Create(MachineNames names, DateTimeOffset now)
    {
        using ECDsa key = ECDsa.Create(ECCurve.NamedCurves.nistP256);

        CertificateRequest request = new(
            $"CN=TivuStream PIE ({names.DnsNames.Skip(MachineNames.LoopbackNames.Length).FirstOrDefault() ?? "localhost"})",
            key,
            HashAlgorithmName.SHA256);

        // Not an authority: it cannot sign another certificate.
        request.CertificateExtensions.Add(new X509BasicConstraintsExtension(false, false, 0, critical: true));
        request.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.DigitalSignature, critical: true));
        request.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension([new Oid("1.3.6.1.5.5.7.3.1")], critical: false));
        request.CertificateExtensions.Add(new X509SubjectKeyIdentifierExtension(request.PublicKey, critical: false));

        SubjectAlternativeNameBuilder alternatives = new();

        foreach (string name in names.DnsNames)
        {
            alternatives.AddDnsName(name);
        }

        foreach (IPAddress address in names.Addresses)
        {
            alternatives.AddIpAddress(address);
        }

        request.CertificateExtensions.Add(alternatives.Build());

        // A day in the past, so that a device whose clock runs slightly
        // behind does not see a certificate that is not valid yet.
        return request.CreateSelfSigned(now.AddDays(-1), now.Add(Validity));
    }

    /// <summary>
    /// Whether a kept certificate must be replaced.
    /// </summary>
    internal static bool NeedsRenewal(X509Certificate2 certificate, MachineNames names, DateTimeOffset now)
    {
        if (certificate.NotAfter.ToUniversalTime() - now.UtcDateTime < RenewalMargin)
        {
            return true;
        }

        // A name or an address the certificate does not carry would make the
        // browser refuse it for the name PIE is reached by. Names it carries
        // that the computer no longer has are harmless.
        HashSet<string> carried = NamesOf(certificate);

        return !names.All().All(carried.Contains);
    }

    /// <summary>
    /// The names and addresses a certificate carries.
    /// </summary>
    internal static HashSet<string> NamesOf(X509Certificate2 certificate)
    {
        HashSet<string> carried = new(StringComparer.OrdinalIgnoreCase);

        foreach (X509SubjectAlternativeNameExtension extension in certificate.Extensions.OfType<X509SubjectAlternativeNameExtension>())
        {
            carried.UnionWith(extension.EnumerateDnsNames());
            carried.UnionWith(extension.EnumerateIPAddresses().Select(address => address.ToString()));
        }

        return carried;
    }

    /// <summary>
    /// The SHA-256 fingerprint, written as browsers show it.
    /// </summary>
    internal static string Fingerprint(X509Certificate2 certificate)
    {
        return string.Join(':', certificate.GetCertHash(HashAlgorithmName.SHA256).Select(b => b.ToString("X2", System.Globalization.CultureInfo.InvariantCulture)));
    }

    /// <summary>
    /// Writes a file only the user running PIE can read.
    /// </summary>
    /// <remarks>
    /// The permissions are set when the file is created, so that the key is
    /// never readable by others, not even for an instant.
    /// </remarks>
    private static void WriteProtected(string path, byte[] content)
    {
        File.Delete(path);

        if (OperatingSystem.IsWindows())
        {
            FileSecurity security = new();

            // Nothing inherited from the folder: only the rule below applies.
            security.SetAccessRuleProtection(isProtected: true, preserveInheritance: false);
            security.AddAccessRule(new FileSystemAccessRule(
                WindowsIdentity.GetCurrent().User!,
                FileSystemRights.FullControl,
                AccessControlType.Allow));

            using FileStream stream = new FileInfo(path).Create(
                FileMode.CreateNew,
                FileSystemRights.FullControl,
                FileShare.None,
                bufferSize: 4096,
                FileOptions.None,
                security);

            stream.Write(content);
        }
        else
        {
            using FileStream stream = new(path, new FileStreamOptions
            {
                Mode = FileMode.CreateNew,
                Access = FileAccess.Write,
                UnixCreateMode = UnixFileMode.UserRead | UnixFileMode.UserWrite,
            });

            stream.Write(content);
        }
    }
}
