using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;

namespace TivuStream.Pie.Api.Transport;

/// <summary>
/// The names and addresses by which this computer can be reached.
/// </summary>
/// <remarks>
/// They go into the certificate generated by PIE, and are the names it
/// answers to. Read at start: an address the router changes later is picked up
/// at the next start (Transport Security Specification, Known Limits).
/// </remarks>
internal sealed record MachineNames(IReadOnlyList<string> DnsNames, IReadOnlyList<IPAddress> Addresses)
{
    /// <summary>
    /// The names of the loopback, always present.
    /// </summary>
    internal static readonly string[] LoopbackNames = ["localhost"];

    /// <summary>
    /// Reads the names of this computer, adding those configured.
    /// </summary>
    /// <param name="configured">Names from <c>Transport:Names</c>.</param>
    internal static MachineNames Discover(IEnumerable<string> configured)
    {
        List<IPAddress> addresses = [IPAddress.Loopback, IPAddress.IPv6Loopback];

        foreach (NetworkInterface adapter in NetworkInterface.GetAllNetworkInterfaces())
        {
            if (adapter.OperationalStatus != OperationalStatus.Up
                || adapter.NetworkInterfaceType == NetworkInterfaceType.Loopback)
            {
                continue;
            }

            foreach (UnicastIPAddressInformation unicast in adapter.GetIPProperties().UnicastAddresses)
            {
                IPAddress address = unicast.Address;

                // A link-local IPv6 address needs its interface to be named in
                // the address, and no browser address bar accepts one.
                bool usable = address.AddressFamily == AddressFamily.InterNetwork
                    || (address.AddressFamily == AddressFamily.InterNetworkV6 && !address.IsIPv6LinkLocal);

                if (usable && !addresses.Contains(address))
                {
                    addresses.Add(address);
                }
            }
        }

        List<string> names = [.. LoopbackNames, Dns.GetHostName()];

        foreach (string name in configured.Select(name => name.Trim()).Where(name => name.Length > 0))
        {
            if (IPAddress.TryParse(name, out IPAddress? address))
            {
                if (!addresses.Contains(address))
                {
                    addresses.Add(address);
                }
            }
            else
            {
                names.Add(name);
            }
        }

        return new MachineNames(
            names.Distinct(StringComparer.OrdinalIgnoreCase).ToList(),
            addresses);
    }

    /// <summary>
    /// Every name and address, as a browser writes them in an address.
    /// </summary>
    internal IEnumerable<string> All()
    {
        return DnsNames.Concat(Addresses.Select(address => address.ToString()));
    }

    /// <summary>
    /// Every name and address, as they arrive in the <c>Host</c> header: an
    /// IPv6 address between brackets.
    /// </summary>
    internal IEnumerable<string> HostNames()
    {
        return DnsNames.Concat(Addresses.Select(address =>
            address.AddressFamily == AddressFamily.InterNetworkV6 ? $"[{address}]" : address.ToString()));
    }
}
