namespace TivuStream.Pie.Api.Transport;

/// <summary>
/// How PIE is reached. Bound to the <c>Transport</c> section.
/// </summary>
/// <remarks>
/// Transport Security Specification, Configuration.
/// </remarks>
internal sealed class TransportOptions
{
    /// <summary>
    /// Port of the plain channel, on the loopback only.
    /// </summary>
    public int HttpPort { get; set; } = 5000;

    /// <summary>
    /// Port of the encrypted channel, on every interface. Zero keeps PIE off
    /// the network.
    /// </summary>
    public int HttpsPort { get; set; } = 5443;

    /// <summary>
    /// Names PIE is reached by that the computer does not know of itself.
    /// </summary>
    public List<string> Names { get; set; } = [];

    /// <summary>
    /// Where the certificate generated by PIE is kept.
    /// </summary>
    public string CertificateDirectory { get; set; } = "data/tls";

    /// <summary>
    /// A certificate of the operator's own, in place of the generated one.
    /// </summary>
    public CertificateOptions Certificate { get; set; } = new();

    /// <summary>
    /// Addresses of the proxies whose forwarding headers are believed.
    /// </summary>
    public List<string> TrustedProxies { get; set; } = [];
}

/// <summary>
/// A certificate provided by the operator.
/// </summary>
internal sealed class CertificateOptions
{
    /// <summary>
    /// The certificate, PFX or PEM. Empty when PIE generates its own.
    /// </summary>
    public string Path { get; set; } = "";

    /// <summary>
    /// The key of a PEM certificate.
    /// </summary>
    public string KeyPath { get; set; } = "";

    /// <summary>
    /// The password of a PFX certificate. Only in <c>appsettings.Local.json</c>.
    /// </summary>
    public string Password { get; set; } = "";

    /// <summary>
    /// Whether the operator provided one.
    /// </summary>
    public bool IsProvided => !string.IsNullOrWhiteSpace(Path);
}
