namespace TivuStream.Pie.Api.Transport;

/// <summary>
/// How PIE is reached. Bound to the <c>Transport</c> section.
/// </summary>
/// <remarks>
/// Transport Security Specification, Configuration.
/// </remarks>
internal sealed class TransportOptions
{
    /// <summary>
    /// Port of the plain channel, on the loopback only.
    /// </summary>
    public int HttpPort { get; set; } = 5000;

    /// <summary>
    /// Port of the encrypted channel, on every interface. Zero keeps PIE off
    /// the network.
    /// </summary>
    public int HttpsPort { get; set; } = 5443;

    /// <summary>
    /// Names PIE is reached by that the computer does not know of itself.
    /// </summary>
    public List<string> Names { get; set; } = [];

    /// <summary>
    /// Where the certificate generated by PIE is kept.
    /// </summary>
    public string CertificateDirectory { get; set; } = "data/tls";
}
