using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.Server.Kestrel.Core;

namespace TivuStream.Pie.Api.Transport;

/// <summary>
/// Opens the channels PIE listens on.
/// </summary>
/// <remarks>
/// Transport Security Specification, Listening. The plain channel on the
/// loopback only: from another device there is no address in clear to try a
/// password on. The encrypted channel on every interface, unless its port is
/// zero.
/// </remarks>
internal static partial class TransportSetup
{
    /// <param name="webHost">The host being built.</param>
    /// <param name="options">The transport settings.</param>
    /// <param name="names">Names and addresses of this computer.</param>
    /// <param name="provided">The operator's certificate, or null to use the generated one.</param>
    internal static void UseTransport(
        this ConfigureWebHostBuilder webHost,
        TransportOptions options,
        MachineNames names,
        X509Certificate2? provided)
    {
        webHost.ConfigureKestrel(kestrel =>
        {
            kestrel.ListenLocalhost(options.HttpPort);

            if (options.HttpsPort <= 0)
            {
                return;
            }

            // Prepared when the server starts, not when the host is built, so
            // that a test host never generates a certificate.
            TimeProvider time = kestrel.ApplicationServices.GetRequiredService<TimeProvider>();
            ILogger logger = kestrel.ApplicationServices.GetRequiredService<ILoggerFactory>().CreateLogger(typeof(TransportSetup));

            (X509Certificate2 certificate, bool generated) = provided is not null
                ? (provided, false)
                : GeneratedCertificate.LoadOrCreate(options.CertificateDirectory, names, time.GetUtcNow());

            kestrel.ListenAnyIP(options.HttpsPort, listen =>
            {
                listen.Protocols = HttpProtocols.Http1AndHttp2;
                listen.UseHttps(certificate);
            });

            Announce(logger, options.HttpsPort, names, certificate, provided is not null ? "provided by the operator" : generated ? "generated now" : "generated by PIE");
        });
    }

    /// <summary>
    /// Says where PIE is reachable, and with which certificate.
    /// </summary>
    /// <remarks>
    /// The fingerprint is not a secret: it is what the person compares with
    /// the one the browser shows, to know they are talking to their own PIE.
    /// The addresses are this computer's, not the network's.
    /// </remarks>
    private static void Announce(ILogger logger, int port, MachineNames names, X509Certificate2 certificate, string origin)
    {
        if (!logger.IsEnabled(LogLevel.Information))
        {
            return;
        }

        string list = Environment.NewLine + string.Join(Environment.NewLine, Addresses(port, names).Select(url => $"  {url}"));
        string until = certificate.NotAfter.ToUniversalTime().ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture);
        string fingerprint = GeneratedCertificate.Fingerprint(certificate);

        Reachable(logger, list, origin, until, fingerprint);
    }

    /// <summary>
    /// The addresses other devices reach PIE at: this computer's names and
    /// its addresses on the network, never the loopback.
    /// </summary>
    internal static IEnumerable<string> Addresses(int port, MachineNames names)
    {
        return names.DnsNames
            .Skip(MachineNames.LoopbackNames.Length)
            .Concat(names.Addresses
                .Where(address => address.AddressFamily == AddressFamily.InterNetwork && !IPAddress.IsLoopback(address))
                .Select(address => address.ToString()))
            .Select(host => $"https://{host}:{port}");
    }

    [LoggerMessage(
        Level = LogLevel.Information,
        Message = "PIE is reachable at:{Urls}\nCertificate {Origin}, valid until {Until}.\nSHA-256 fingerprint: {Fingerprint}")]
    private static partial void Reachable(ILogger logger, string urls, string origin, string until, string fingerprint);
}
